version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=library-db
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=library
    expose:
      - '5432'
