server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo-db
    username: todo
    password: todo
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none